development:
  adapter: postgresql
  database: cyrillelabesse
  username: clabesse
  password: 
test:
  adapter: postgresql
  database: cyrillelabesse_test
  username: clabesse
  password: 
production:
  adapter: postgresql
  database: cyrillelabesse
  username: clabesse
  password: 
