development:
  adapter: mysql2
  database: cyrillelabesse
  username: root
  password: 
test:
  adapter: mysql2
  database: cyrillelabesse_test
  username: root
  password: 
production:
  adapter: mysql2
  database: cyrillelabesse
  username: root
  password: 
